tunnel: b87dc12c-7ad8-4d75-a953-749f1c60722c
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: monitor.smartlockerhcmute.dpdns.org
    service: http://smartlocker-monitor:8001
  - hostname: app.smartlockerhcmute.dpdns.org
    service: http://smartlocker-app:8000
  - service: http_status:404
