tunnel: smartlocker
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: monitor-smartlocker.example.com
    service: http://monitor:8001
  - hostname: app-smartlocker.example.com
    service: http://app:8000
  - service: http_status:404
