tunnel: b87dc12c-7ad8-4d75-a953-749f1c60722c
credentials-file: /root/.cloudflared/<tunnel-id>.json

ingress:
  - hostname: monitor-smartlocker.example.com
    service: http://127.0.0.1:8001
  - hostname: app-smartlocker.example.com
    service: http://127.0.0.1:8000
  - service: http_status:404
